language: python
python: 2.7
env:
  - TOX_ENV=py27-dj15
  - TOX_ENV=py27-dj16
  - TOX_ENV=pep8

matrix:
  allow_failures:
    - env: TOX_ENV=pep8

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
